# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E3E2D8
background         #2B2A23
cursor             #8B8984

active_tab_foreground     #2B2A23
active_tab_background     #E3E2D8
inactive_tab_foreground   #E3E2D8
inactive_tab_background   #2B2A23

active_border_color   #E3E2D8
inactive_border_color #2B2A23
bell_border_color     #1F2101

color0      #504F47
color1		#1F2101
color2		#252425
color3		#2C274D
color4		#2D2852
color5		#4B5440
color6		#84816B
color7		#CFCDBF
color8		#919085
color9		#2A2C01
color10		#323031
color11		#3B3467
color12		#3C356E
color13		#647055
color14		#B0AC8F
color15		#CFCDBF
